### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by dervaux** [lukeed/ley#20]
Dear @lukeed,
I've been trying to implement ley with Typescript. After following your documentation and implementing this issue's solution: https://github.com/lukeed/ley/issues/13, I'm still getting this ts error message:
<img width="421" alt="Screenshot 2021-06-24 at 18 16 36" src="https://user-images.githubusercontent.com/34522733/123297965-552ee480-d518-11eb-8ec0-28119f665094.png">
`'1624547133-create-users-table.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.ts(1208)
var exports: any`
Any idea about what could be missing here?

**Comment by jgod** [comment]
Don't use module.exports. prepend your function declaration with `export` instead. `export async function up(sql) {`
