### ISSUE TITLE
Question: exits grabs all migrations

### ISSUE THREAD

**Issue by lukasa1993** [lukeed/ley#29]
any way it can grab only last one ? or is there any need to grab all of them ? 

i see it does diff but since its forward only wouldn't it be same to just continue from last one?

**Comment by lukeed** [comment]
Not sure what you’re asking. Migrations are alphasorted and it continues from the last-applied migration. This way if you have run 01, 02, and 04 you wouldn’t be able to add 03 later and expect it to run

**Comment by lukasa1993** [comment]
from text.js exist query i am under impression it grabs whole table not last one and it diffs it agains whole folder

**Comment by lukeed** [comment]
It doesn’t matter. 5k migration names coming from the table is going to be done in 1ms or less across all DB engines
